// This file was auto-generated by Fern from our API Definition.

import * as Darwin from "../../../src/api/index";
import { DarwinClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("BusinessesClient", () => {
    test("listAIs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            ais: [
                {
                    id: "id",
                    type: "personal",
                    name: "name",
                    handle: "handle",
                    avatarUrl: "avatarUrl",
                    description: "description",
                    links: [{ key: "value" }],
                    capabilities: [{ key: "value" }],
                    location: { key: "value" },
                    organization: { key: "value" },
                    visibility: "PUBLIC",
                    accessPolicyId: "accessPolicyId",
                    status: "status",
                    profile: { key: "value" },
                    role: "owner",
                },
            ],
        };

        server.mockEndpoint().get("/ais").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.supply.businesses.listAIs();
        expect(response).toEqual(rawResponseBody);
    });

    test("listAIs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.businesses.listAIs();
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listAIs (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.businesses.listAIs();
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listAIs (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.businesses.listAIs();
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listAIs (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.businesses.listAIs();
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createAI (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            ai: {
                id: "id",
                type: "personal",
                name: "name",
                handle: "handle",
                avatarUrl: "avatarUrl",
                description: "description",
                links: [{ key: "value" }],
                capabilities: [{ key: "value" }],
                location: { key: "value" },
                organization: { key: "value" },
                visibility: "PUBLIC",
                accessPolicyId: "accessPolicyId",
                status: "status",
                profile: { key: "value" },
                role: "owner",
            },
        };

        server
            .mockEndpoint()
            .post("/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.supply.businesses.createAi({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createAI (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.businesses.createAi({
                name: "name",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createAI (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.businesses.createAi({
                name: "name",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createAI (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.businesses.createAi({
                name: "name",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createAI (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.businesses.createAi({
                name: "name",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("getAI (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            ai: {
                id: "id",
                type: "personal",
                name: "name",
                handle: "handle",
                avatarUrl: "avatarUrl",
                description: "description",
                links: [{ key: "value" }],
                capabilities: [{ key: "value" }],
                location: { key: "value" },
                organization: { key: "value" },
                visibility: "PUBLIC",
                accessPolicyId: "accessPolicyId",
                status: "status",
                profile: { key: "value" },
                role: "owner",
            },
        };

        server.mockEndpoint().get("/ais/aiId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.supply.businesses.getAi({
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getAI (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.businesses.getAi({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getAI (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.businesses.getAi({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getAI (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.businesses.getAi({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getAI (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.businesses.getAi({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("updateAI (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            ai: {
                id: "id",
                type: "personal",
                name: "name",
                handle: "handle",
                avatarUrl: "avatarUrl",
                description: "description",
                links: [{ key: "value" }],
                capabilities: [{ key: "value" }],
                location: { key: "value" },
                organization: { key: "value" },
                visibility: "PUBLIC",
                accessPolicyId: "accessPolicyId",
                status: "status",
                profile: { key: "value" },
                role: "owner",
            },
        };

        server
            .mockEndpoint()
            .patch("/ais/aiId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.supply.businesses.updateAi({
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateAI (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.businesses.updateAi({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("updateAI (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.businesses.updateAi({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("updateAI (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.businesses.updateAi({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("updateAI (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.businesses.updateAi({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });
});
