// This file was auto-generated by Fern from our API Definition.

import * as Darwin from "../../../src/api/index";
import { DarwinClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("EarningsClient", () => {
    test("getAIBillingSummary (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            currency: "usd",
            account: { autoTopup: { enabled: true, thresholdMinor: 1, amountMinor: 1 }, payoutSchedule: "manual" },
            wallet: {
                promotional: 1,
                funded: 1,
                earned: 1,
                pendingEarned: 1,
                reserved: 1,
                earnedDeficit: 1,
                spendable: 1,
                withdrawable: 1,
            },
            actions: { canWithdraw: true, hasPaymentMethod: true, payoutReady: true },
            feePolicy: {
                standardPayout: { variableBps: 1, fixedMinor: 1 },
                instantPayout: { variableBps: 1, fixedMinor: 1 },
                instantPayoutIncludesStandardConnectCost: true,
            },
        };

        server.mockEndpoint().get("/ais/aiId/billing").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.supply.earnings.getAiBillingSummary({
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getAIBillingSummary (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/billing").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.earnings.getAiBillingSummary({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getAIBillingSummary (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/billing").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.earnings.getAiBillingSummary({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getAIBillingSummary (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/billing").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.earnings.getAiBillingSummary({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getAIBillingSummary (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/ais/aiId/billing").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.supply.earnings.getAiBillingSummary({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("listAIBillingActivity (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            wallet: [
                {
                    id: "id",
                    kind: "kind",
                    availableDeltaMinor: 1,
                    reservedDeltaMinor: 1,
                    currency: "currency",
                    createdAt: "2024-01-15T09:30:00Z",
                },
            ],
            nextCursor: { wallet: "wallet" },
        };

        server
            .mockEndpoint()
            .get("/ais/aiId/billing/activity")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.supply.earnings.listAiBillingActivity({
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listAIBillingActivity (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/ais/aiId/billing/activity")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.listAiBillingActivity({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listAIBillingActivity (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/ais/aiId/billing/activity")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.listAiBillingActivity({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listAIBillingActivity (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/ais/aiId/billing/activity")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.listAiBillingActivity({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listAIBillingActivity (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/ais/aiId/billing/activity")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.listAiBillingActivity({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createAIPaymentMethodSetup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { clientSecret: "clientSecret", publishableKey: "publishableKey" };

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/payment-method-setup")
            .header("Idempotency-Key", "Idempotency-Key")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.supply.earnings.createAiPaymentMethodSetup({
            "Idempotency-Key": "Idempotency-Key",
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createAIPaymentMethodSetup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/payment-method-setup")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiPaymentMethodSetup({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createAIPaymentMethodSetup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/payment-method-setup")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiPaymentMethodSetup({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createAIPaymentMethodSetup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/payment-method-setup")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiPaymentMethodSetup({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createAIPaymentMethodSetup (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/payment-method-setup")
            .header("Idempotency-Key", "idempotencyKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiPaymentMethodSetup({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createAIWalletTopup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 1 };
        const rawResponseBody = {
            clientSecret: "clientSecret",
            publishableKey: "publishableKey",
            amountMinor: 1,
            walletCreditAmountMinor: 1,
            currency: "usd",
        };

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/wallet-topups")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.supply.earnings.createAiWalletTopup({
            "Idempotency-Key": "Idempotency-Key",
            aiId: "aiId",
            amountMinor: 1,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createAIWalletTopup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 99999999 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/wallet-topups")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiWalletTopup({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                amountMinor: 99999999,
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createAIWalletTopup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 99999999 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/wallet-topups")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiWalletTopup({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                amountMinor: 99999999,
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createAIWalletTopup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 99999999 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/wallet-topups")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiWalletTopup({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                amountMinor: 99999999,
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createAIWalletTopup (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 99999999 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/wallet-topups")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiWalletTopup({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                amountMinor: 99999999,
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("updateAIMoneySettings (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            autoTopup: { enabled: true, thresholdMinor: 1, amountMinor: 1 },
            payoutSchedule: "manual",
        };

        server
            .mockEndpoint()
            .patch("/ais/aiId/billing/money-settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.supply.earnings.updateAiMoneySettings({
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateAIMoneySettings (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/billing/money-settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.updateAiMoneySettings({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("updateAIMoneySettings (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/billing/money-settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.updateAiMoneySettings({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("updateAIMoneySettings (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/billing/money-settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.updateAiMoneySettings({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("updateAIMoneySettings (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/ais/aiId/billing/money-settings")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.updateAiMoneySettings({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("quoteAIWalletWithdrawal (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 1 };
        const rawResponseBody = {
            speed: "STANDARD",
            withdrawalAmountMinor: 1,
            providerFeeMinor: 1,
            payoutAmountMinor: 1,
            rate: { variableBps: 1, fixedMinor: 1 },
            currency: "usd",
        };

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/withdrawal-quotes")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.supply.earnings.quoteAiWalletWithdrawal({
            aiId: "aiId",
            body: {
                amountMinor: 1,
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("quoteAIWalletWithdrawal (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/withdrawal-quotes")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.quoteAiWalletWithdrawal({
                aiId: "aiId",
                body: {
                    amountMinor: 1,
                },
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("quoteAIWalletWithdrawal (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/withdrawal-quotes")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.quoteAiWalletWithdrawal({
                aiId: "aiId",
                body: {
                    amountMinor: 1,
                },
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("quoteAIWalletWithdrawal (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/withdrawal-quotes")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.quoteAiWalletWithdrawal({
                aiId: "aiId",
                body: {
                    amountMinor: 1,
                },
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("quoteAIWalletWithdrawal (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/withdrawal-quotes")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.quoteAiWalletWithdrawal({
                aiId: "aiId",
                body: {
                    amountMinor: 1,
                },
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createAIWalletWithdrawal (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 1 };
        const rawResponseBody = {
            id: "id",
            status: "submitted",
            withdrawalAmountMinor: 1,
            providerFeeMinor: 1,
            payoutAmountMinor: 1,
            speed: "standard",
            failureCode: "failureCode",
        };

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/withdrawals")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.supply.earnings.createAiWalletWithdrawal({
            "Idempotency-Key": "Idempotency-Key",
            aiId: "aiId",
            body: {
                amountMinor: 1,
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createAIWalletWithdrawal (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/withdrawals")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiWalletWithdrawal({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                body: {
                    amountMinor: 1,
                },
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createAIWalletWithdrawal (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/withdrawals")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiWalletWithdrawal({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                body: {
                    amountMinor: 1,
                },
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createAIWalletWithdrawal (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/withdrawals")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiWalletWithdrawal({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                body: {
                    amountMinor: 1,
                },
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createAIWalletWithdrawal (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { amountMinor: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/withdrawals")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiWalletWithdrawal({
                "Idempotency-Key": "idempotencyKey",
                aiId: "aiId",
                body: {
                    amountMinor: 1,
                },
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createAIPayoutMethodSetup (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { url: "url" };

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/payout-method-setup")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.supply.earnings.createAiPayoutMethodSetup({
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createAIPayoutMethodSetup (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/payout-method-setup")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiPayoutMethodSetup({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createAIPayoutMethodSetup (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/payout-method-setup")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiPayoutMethodSetup({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createAIPayoutMethodSetup (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/payout-method-setup")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiPayoutMethodSetup({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createAIPayoutMethodSetup (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/ais/aiId/billing/payout-method-setup")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.supply.earnings.createAiPayoutMethodSetup({
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });
});
