// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         skillId: "skillId"
 *     }
 */
export interface DeleteAiSkillSkillsRequest {
    aiId: string;
    skillId: string;
}
