// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         transactionId: "transactionId",
 *         type: "STRIPE_SHARED_PAYMENT_TOKEN",
 *         networkProfileId: "networkProfileId",
 *         grantedToken: "grantedToken"
 *     }
 */
export interface ApplicationPaymentAuthorizationRequest {
    transactionId: string;
    /** A caller-generated key, unique to this operation and payload. */
    "Idempotency-Key": string;
    type: ApplicationPaymentAuthorizationRequest.Type;
    /** Darwin seller network identifier used when the application provisions the SPT. */
    networkProfileId: string;
    /** One transaction-scoped, time-limited Stripe Shared Payment Token. */
    grantedToken: string;
}

export namespace ApplicationPaymentAuthorizationRequest {
    export const Type = {
        StripeSharedPaymentToken: "STRIPE_SHARED_PAYMENT_TOKEN",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
