// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         transactionId: "transactionId"
 *     }
 */
export interface GetTransactionAccountRequirementTransactionsRequest {
    transactionId: string;
    /** Optional explicit AI scope. When omitted, Darwin uses the caller’s selected AI. */
    aiId?: string;
}
