// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { ApplicationsClient } from "../resources/applications/client/Client.js";
import { EnrollmentClient } from "../resources/enrollment/client/Client.js";
import { EphemeralGoalsClient } from "../resources/ephemeralGoals/client/Client.js";
import { UsersClient } from "../resources/users/client/Client.js";
import { WebhooksClient } from "../resources/webhooks/client/Client.js";

export declare namespace ConnectClient {
    export type Options = BaseClientOptions;
}

export class ConnectClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ConnectClient.Options>;
    protected _applications: ApplicationsClient | undefined;
    protected _users: UsersClient | undefined;
    protected _enrollment: EnrollmentClient | undefined;
    protected _ephemeralGoals: EphemeralGoalsClient | undefined;
    protected _webhooks: WebhooksClient | undefined;

    constructor(options: ConnectClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get applications(): ApplicationsClient {
        return (this._applications ??= new ApplicationsClient(this._options));
    }

    public get users(): UsersClient {
        return (this._users ??= new UsersClient(this._options));
    }

    public get enrollment(): EnrollmentClient {
        return (this._enrollment ??= new EnrollmentClient(this._options));
    }

    public get ephemeralGoals(): EphemeralGoalsClient {
        return (this._ephemeralGoals ??= new EphemeralGoalsClient(this._options));
    }

    public get webhooks(): WebhooksClient {
        return (this._webhooks ??= new WebhooksClient(this._options));
    }
}
