// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as Darwin from "../index.js";

export class TooManyRequestsError extends errors.DarwinError {
    public declare readonly body: Darwin.Error_;

    constructor(body: Darwin.Error_, rawResponse?: core.RawResponse) {
        super({
            message: "TooManyRequestsError",
            statusCode: 429,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "TooManyRequestsError";
    }
}
