// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         connectionId: "connectionId",
 *         toolkit: "toolkit"
 *     }
 */
export interface DisableConnectionGrantConnectionsRequest {
    aiId: string;
    connectionId: string;
    toolkit: string;
}
