// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../../../../../../index.js";

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         listings: [{
 *                 type: "PRODUCT",
 *                 executionDomain: "HUMAN",
 *                 title: "title"
 *             }]
 *     }
 */
export interface BatchUpsertListingsRequest {
    aiId: string;
    listings: Darwin.CreateListingRequest[];
}
