// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         listingId: "listingId"
 *     }
 */
export interface GetListingListingsRequest {
    aiId: string;
    listingId: string;
}
