// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../../../../../../index.js";

/**
 * @example
 *     {
 *         aiId: "aiId"
 *     }
 */
export interface ListListingsListingsRequest {
    aiId: string;
    limit?: number;
    cursor?: string;
    q?: string;
    type?: Darwin.ListingType;
    executionDomain?: Darwin.ListingExecutionDomain;
    capabilityKind?: Darwin.supply.ListListingsListingsRequestCapabilityKind;
    status?: Darwin.ListingStatus;
    visibility?: Darwin.ListingVisibility;
}
