// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Darwin from "../../../index.js";

export declare namespace DealsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class DealsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DealsClient.Options>;

    constructor(options: DealsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns the commercial work owned by the selected AI. Darwin handles counterpart discovery and coordination behind the scenes.
     *
     * @param {Darwin.ListDealsDealsRequest} request
     * @param {DealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.deals.listDeals()
     */
    public listDeals(
        request: Darwin.ListDealsDealsRequest = {},
        requestOptions?: DealsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.ListDealsDealsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listDeals(request, requestOptions));
    }

    private async __listDeals(
        request: Darwin.ListDealsDealsRequest = {},
        requestOptions?: DealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ListDealsDealsResponse>> {
        const { aiId } = request;
        const _queryParams: Record<string, unknown> = {
            aiId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                "deals",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ListDealsDealsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/deals");
    }

    /**
     * Creates a private draft for terms, counterparty context, payment, and delivery. Darwin coordinates the required work on the AI’s behalf.
     *
     * @param {Darwin.CreateDealRequest} request
     * @param {DealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.deals.createDeal({
     *         mode: "BUY",
     *         title: "title"
     *     })
     */
    public createDeal(
        request: Darwin.CreateDealRequest,
        requestOptions?: DealsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.CreateDealDealsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createDeal(request, requestOptions));
    }

    private async __createDeal(
        request: Darwin.CreateDealRequest,
        requestOptions?: DealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.CreateDealDealsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                "deals",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.CreateDealDealsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/deals");
    }

    /**
     * @param {Darwin.GetDealDealsRequest} request
     * @param {DealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.deals.getDeal({
     *         dealId: "dealId"
     *     })
     */
    public getDeal(
        request: Darwin.GetDealDealsRequest,
        requestOptions?: DealsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.GetDealDealsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getDeal(request, requestOptions));
    }

    private async __getDeal(
        request: Darwin.GetDealDealsRequest,
        requestOptions?: DealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.GetDealDealsResponse>> {
        const { dealId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `deals/${core.url.encodePathParam(dealId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.GetDealDealsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/deals/{dealId}");
    }

    /**
     * Only a draft deal can be edited directly.
     *
     * @param {Darwin.UpdateDealRequest} request
     * @param {DealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.deals.updateDeal({
     *         dealId: "dealId"
     *     })
     */
    public updateDeal(
        request: Darwin.UpdateDealRequest,
        requestOptions?: DealsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.UpdateDealDealsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateDeal(request, requestOptions));
    }

    private async __updateDeal(
        request: Darwin.UpdateDealRequest,
        requestOptions?: DealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.UpdateDealDealsResponse>> {
        const { dealId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `deals/${core.url.encodePathParam(dealId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.UpdateDealDealsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/deals/{dealId}");
    }

    /**
     * @param {Darwin.DealActionRequest} request
     * @param {DealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.deals.actOnDeal({
     *         dealId: "dealId",
     *         action: "SEND"
     *     })
     */
    public actOnDeal(
        request: Darwin.DealActionRequest,
        requestOptions?: DealsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.ActOnDealDealsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__actOnDeal(request, requestOptions));
    }

    private async __actOnDeal(
        request: Darwin.DealActionRequest,
        requestOptions?: DealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ActOnDealDealsResponse>> {
        const { dealId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `deals/${core.url.encodePathParam(dealId)}/actions`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ActOnDealDealsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/deals/{dealId}/actions");
    }

    /**
     * @param {Darwin.ListDealPaymentsDealsRequest} request
     * @param {DealsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.deals.listDealPayments({
     *         dealId: "dealId"
     *     })
     */
    public listDealPayments(
        request: Darwin.ListDealPaymentsDealsRequest,
        requestOptions?: DealsClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.ListDealPaymentsDealsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listDealPayments(request, requestOptions));
    }

    private async __listDealPayments(
        request: Darwin.ListDealPaymentsDealsRequest,
        requestOptions?: DealsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.ListDealPaymentsDealsResponse>> {
        const { dealId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `deals/${core.url.encodePathParam(dealId)}/payments`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.ListDealPaymentsDealsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/deals/{dealId}/payments");
    }
}
