// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {}
 *     }
 */
export interface RequestTaskPublicationTasksRequest {
    id: string;
    body: Darwin.PublicationRequest;
}
