// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Darwin from "../../../index.js";

export declare namespace SearchClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SearchClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SearchClient.Options>;

    constructor(options: SearchClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Runs synchronous FAST search over public Listings. Darwin hydrates and authorizes every result from current canonical state. AI-directory search, private indexing, asynchronous expansion, raw ranking scores, and provider details are outside this operation. Requires `directory:read`.
     *
     * @param {Darwin.SearchRequest} request
     * @param {SearchClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link Darwin.TooManyRequestsError}
     * @throws {@link Darwin.ServiceUnavailableError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.search.searchNetworkSupply({
     *         query: "query"
     *     })
     */
    public searchNetworkSupply(
        request: Darwin.SearchRequest,
        requestOptions?: SearchClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.SearchResponse> {
        return core.HttpResponsePromise.fromPromise(this.__searchNetworkSupply(request, requestOptions));
    }

    private async __searchNetworkSupply(
        request: Darwin.SearchRequest,
        requestOptions?: SearchClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.SearchResponse>> {
        const { "X-Request-Id": requestId, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({ "X-Request-Id": requestId }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                "search",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.SearchResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 429:
                    throw new Darwin.TooManyRequestsError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 503:
                    throw new Darwin.ServiceUnavailableError(
                        _response.error.body as Darwin.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/search");
    }
}
