// This file was auto-generated by Fern from our API Definition.

export interface ApplicationMonetizationPolicy {
    applicationId: string;
    mode: ApplicationMonetizationPolicy.Mode;
    currency: string;
    fixedAmountMinor?: (number | null) | undefined;
    percentageBps?: (number | null) | undefined;
    maximumFeeMinor?: (number | null) | undefined;
    /** Stored payout preference. Fee withdrawal and scheduled payout operations remain preview until their public endpoints ship. */
    payoutSchedule: ApplicationMonetizationPolicy.PayoutSchedule;
    status: ApplicationMonetizationPolicy.Status;
    revision: number;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
}

export namespace ApplicationMonetizationPolicy {
    export const Mode = {
        None: "NONE",
        Fixed: "FIXED",
        Percentage: "PERCENTAGE",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    /** Stored payout preference. Fee withdrawal and scheduled payout operations remain preview until their public endpoints ship. */
    export const PayoutSchedule = {
        Manual: "MANUAL",
        Weekly: "WEEKLY",
        Monthly: "MONTHLY",
    } as const;
    export type PayoutSchedule = (typeof PayoutSchedule)[keyof typeof PayoutSchedule];
    export const Status = {
        Active: "ACTIVE",
        Disabled: "DISABLED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
