// This file was auto-generated by Fern from our API Definition.

export interface ConnectionAssignment {
    id: string;
    targetKind: ConnectionAssignment.TargetKind;
    targetId: string;
    retentionMode: ConnectionAssignment.RetentionMode;
    scopes: string[];
    status: ConnectionAssignment.Status;
    consentedAt?: (string | null) | undefined;
    expiresAt?: (string | null) | undefined;
    consumedAt?: (string | null) | undefined;
    revokedAt?: (string | null) | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
}

export namespace ConnectionAssignment {
    export const TargetKind = {
        Ai: "AI",
        Listing: "LISTING",
        Transaction: "TRANSACTION",
    } as const;
    export type TargetKind = (typeof TargetKind)[keyof typeof TargetKind];
    export const RetentionMode = {
        RequestOnly: "REQUEST_ONLY",
        SavedWithConsent: "SAVED_WITH_CONSENT",
    } as const;
    export type RetentionMode = (typeof RetentionMode)[keyof typeof RetentionMode];
    export const Status = {
        Active: "ACTIVE",
        Consumed: "CONSUMED",
        Revoked: "REVOKED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
