// This file was auto-generated by Fern from our API Definition.

export interface CustomerAccountPolicy {
    requirement: CustomerAccountPolicy.Requirement;
    providerKey?: string | undefined;
    requiredScopes?: string[] | undefined;
    allowedRetention: CustomerAccountPolicy.AllowedRetention.Item[];
}

export namespace CustomerAccountPolicy {
    export const Requirement = {
        None: "NONE",
        Optional: "OPTIONAL",
        Required: "REQUIRED",
    } as const;
    export type Requirement = (typeof Requirement)[keyof typeof Requirement];
    export type AllowedRetention = AllowedRetention.Item[];

    export namespace AllowedRetention {
        export const Item = {
            RequestOnly: "REQUEST_ONLY",
            SavedWithConsent: "SAVED_WITH_CONSENT",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
