// This file was auto-generated by Fern from our API Definition.

export const SearchProtocol = {
    Darwin: "DARWIN",
    Ucp: "UCP",
    Acp: "ACP",
    Ard: "ARD",
    A2A: "A2A",
    Mcp: "MCP",
    Webmcp: "WEBMCP",
    Openapi: "OPENAPI",
    X402: "X402",
    Mpp: "MPP",
    Ap2: "AP2",
} as const;
export type SearchProtocol = (typeof SearchProtocol)[keyof typeof SearchProtocol];
