// This file was auto-generated by Fern from our API Definition.

export interface SearchPublicSeller {
    id: string;
    name: string;
    handle: string | null;
    avatarUrl: string | null;
    classification: string | null;
    coarseLocation: string | null;
}
