// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface SearchResponse {
    searchId: string;
    status: SearchResponse.Status;
    results: Darwin.SearchResult[];
    nextCursor: string | null;
    stopReason: SearchResponse.StopReason;
    timingMs: SearchResponse.TimingMs;
}

export namespace SearchResponse {
    export const Status = {
        Complete: "COMPLETE",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const StopReason = {
        MatchFound: "MATCH_FOUND",
        NoEligibleSupply: "NO_ELIGIBLE_SUPPLY",
        ConfidenceTooLow: "CONFIDENCE_TOO_LOW",
        TimeBudgetReached: "TIME_BUDGET_REACHED",
    } as const;
    export type StopReason = (typeof StopReason)[keyof typeof StopReason];

    export interface TimingMs {
        total: number;
    }
}
