// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface SearchPublicListing {
    id: string;
    revision: number;
    type: Darwin.ListingType;
    executionDomain: Darwin.ListingExecutionDomain;
    capabilityKind?: (SearchPublicListing.CapabilityKind | null) | undefined;
    title: string;
    description?: (string | null) | undefined;
    category?: (string | null) | undefined;
    tags: string[];
    mediaPreviewUrl?: (string | null) | undefined;
    price?: (SearchPublicListing.Price | null) | undefined;
    availability?: (SearchPublicListing.Availability | null) | undefined;
    protocolKinds: Darwin.SearchProtocol[];
    seller: Darwin.SearchPublicSeller;
}

export namespace SearchPublicListing {
    export const CapabilityKind = {
        Api: "API",
        BrowserAutomation: "BROWSER_AUTOMATION",
        Mcp: "MCP",
        SoftwareAction: "SOFTWARE_ACTION",
        Other: "OTHER",
    } as const;
    export type CapabilityKind = (typeof CapabilityKind)[keyof typeof CapabilityKind];

    export interface Price {
        currency: string;
        minimumMinor: number | null;
        maximumMinor: number | null;
        unit: string | null;
        chargeType: string;
    }

    export interface Availability {
        status: Availability.Status;
        observedAt: string;
    }

    export namespace Availability {
        export const Status = {
            Available: "AVAILABLE",
            Limited: "LIMITED",
            Unavailable: "UNAVAILABLE",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }
}
