// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../index.js";

export interface SearchFilters {
    listingTypes?: Darwin.ListingType[] | undefined;
    executionDomains?: Darwin.ListingExecutionDomain[] | undefined;
    capabilityKinds?: SearchFilters.CapabilityKinds.Item[] | undefined;
    protocols?: Darwin.SearchProtocol[] | undefined;
    minPriceMinor?: number | undefined;
    maxPriceMinor?: number | undefined;
    currency?: string | undefined;
    allowQuotePricing?: boolean | undefined;
    requiresExecutableRoute?: boolean | undefined;
    availableAt?: string | undefined;
    countryCodes?: string[] | undefined;
}

export namespace SearchFilters {
    export type CapabilityKinds = CapabilityKinds.Item[];

    export namespace CapabilityKinds {
        export const Item = {
            Api: "API",
            BrowserAutomation: "BROWSER_AUTOMATION",
            Mcp: "MCP",
            SoftwareAction: "SOFTWARE_ACTION",
            Other: "OTHER",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
