// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         applicationId: "applicationId",
 *         goalId: "goalId"
 *     }
 */
export interface CastEphemeralGoalEphemeralGoalsRequest {
    applicationId: string;
    goalId: string;
}
