// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         applicationId: "applicationId",
 *         goalId: "goalId",
 *         action: "CANCEL"
 *     }
 */
export interface EphemeralGoalActionRequest {
    applicationId: string;
    goalId: string;
    action: EphemeralGoalActionRequest.Action;
}

export namespace EphemeralGoalActionRequest {
    export const Action = {
        Cancel: "CANCEL",
    } as const;
    export type Action = (typeof Action)[keyof typeof Action];
}
