// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListDealsDealsRequest {
    /** Optional explicit AI scope. When omitted, Darwin uses the caller’s selected AI. */
    aiId?: string;
}
