// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         dealId: "dealId"
 *     }
 */
export interface ListDealPaymentsDealsRequest {
    dealId: string;
}
