// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         assetId: "assetId"
 *     }
 */
export interface DeleteAiAssetAisRequest {
    aiId: string;
    assetId: string;
}
