// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         membershipId: "membershipId"
 *     }
 */
export interface RemoveAiMemberAisRequest {
    aiId: string;
    membershipId: string;
}
