// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../../../../../../index.js";

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         aiId: "aiId",
 *         body: {
 *             amountMinor: 1
 *         }
 *     }
 */
export interface CreateAiWalletWithdrawalEarningsRequest {
    aiId: string;
    /** A caller-generated key, unique to this operation and payload. */
    "Idempotency-Key": string;
    body: Darwin.WithdrawalRequest;
}
