// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId"
 *     }
 */
export interface GetAiBillingSummaryEarningsRequest {
    /** AI whose billing account to inspect. */
    aiId: string;
}
