// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../../../../../../index.js";

/**
 * @example
 *     {
 *         aiId: "aiId",
 *         body: {
 *             amountMinor: 1
 *         }
 *     }
 */
export interface QuoteAiWalletWithdrawalEarningsRequest {
    aiId: string;
    body: Darwin.WithdrawalRequest;
}
