// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId"
 *     }
 */
export interface UpdateMoneySettingsRequest {
    aiId: string;
    autoTopupEnabled?: boolean;
    autoTopupThresholdMinor?: number | null;
    autoTopupAmountMinor?: number | null;
    payoutSchedule?: UpdateMoneySettingsRequest.PayoutSchedule;
}

export namespace UpdateMoneySettingsRequest {
    export const PayoutSchedule = {
        Manual: "manual",
        Monthly: "monthly",
    } as const;
    export type PayoutSchedule = (typeof PayoutSchedule)[keyof typeof PayoutSchedule];
}
