// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { BusinessesClient } from "../resources/businesses/client/Client.js";
import { EarningsClient } from "../resources/earnings/client/Client.js";
import { ListingsClient } from "../resources/listings/client/Client.js";

export declare namespace SupplyClient {
    export type Options = BaseClientOptions;
}

export class SupplyClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SupplyClient.Options>;
    protected _businesses: BusinessesClient | undefined;
    protected _listings: ListingsClient | undefined;
    protected _earnings: EarningsClient | undefined;

    constructor(options: SupplyClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get businesses(): BusinessesClient {
        return (this._businesses ??= new BusinessesClient(this._options));
    }

    public get listings(): ListingsClient {
        return (this._listings ??= new ListingsClient(this._options));
    }

    public get earnings(): EarningsClient {
        return (this._earnings ??= new EarningsClient(this._options));
    }
}
