// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         aiId: "aiId"
 *     }
 */
export interface CreateAiConversationConversationsRequest {
    aiId: string;
}
