// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         outcomeId: "outcomeId"
 *     }
 */
export interface GetOutcomeOutcomesRequest {
    outcomeId: string;
}
