// This file was auto-generated by Fern from our API Definition.

import * as Darwin from "../../../src/api/index";
import { DarwinClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("ApplicationsClient", () => {
    test("listApplications (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            applications: [
                {
                    id: "id",
                    name: "name",
                    slug: "slug",
                    description: "description",
                    websiteUrl: "websiteUrl",
                    mode: "hosted",
                    status: "active",
                    redirectUris: ["redirectUris"],
                    defaultAiKind: "personal",
                    defaultVisibility: "PUBLIC",
                    oauth: {
                        clientId: "clientId",
                        authorizationUrl: "authorizationUrl",
                        tokenUrl: "tokenUrl",
                        requirePKCE: true,
                    },
                    metadata: { key: "value" },
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server.mockEndpoint().get("/applications").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.connect.applications.listApplications();
        expect(response).toEqual(rawResponseBody);
    });

    test("listApplications (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/applications").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.connect.applications.listApplications();
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listApplications (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/applications").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.connect.applications.listApplications();
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listApplications (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/applications").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.connect.applications.listApplications();
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listApplications (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/applications").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.connect.applications.listApplications();
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createApplication (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            application: {
                id: "id",
                name: "name",
                slug: "slug",
                description: "description",
                websiteUrl: "websiteUrl",
                mode: "hosted",
                status: "active",
                redirectUris: ["redirectUris"],
                defaultAiKind: "personal",
                defaultVisibility: "PUBLIC",
                oauth: {
                    clientId: "clientId",
                    authorizationUrl: "authorizationUrl",
                    tokenUrl: "tokenUrl",
                    requirePKCE: true,
                },
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/applications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.applications.createApplication({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createApplication (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.createApplication({
                name: "name",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createApplication (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.createApplication({
                name: "name",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createApplication (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.createApplication({
                name: "name",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createApplication (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.createApplication({
                name: "name",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("getApplication (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            application: {
                id: "id",
                name: "name",
                slug: "slug",
                description: "description",
                websiteUrl: "websiteUrl",
                mode: "hosted",
                status: "active",
                redirectUris: ["redirectUris"],
                defaultAiKind: "personal",
                defaultVisibility: "PUBLIC",
                oauth: {
                    clientId: "clientId",
                    authorizationUrl: "authorizationUrl",
                    tokenUrl: "tokenUrl",
                    requirePKCE: true,
                },
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.applications.getApplication({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getApplication (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getApplication (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getApplication (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getApplication (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("archiveApplication (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            application: {
                id: "id",
                name: "name",
                slug: "slug",
                description: "description",
                websiteUrl: "websiteUrl",
                mode: "hosted",
                status: "active",
                redirectUris: ["redirectUris"],
                defaultAiKind: "personal",
                defaultVisibility: "PUBLIC",
                oauth: {
                    clientId: "clientId",
                    authorizationUrl: "authorizationUrl",
                    tokenUrl: "tokenUrl",
                    requirePKCE: true,
                },
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .delete("/applications/applicationId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.applications.archiveApplication({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("archiveApplication (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.archiveApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("archiveApplication (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.archiveApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("archiveApplication (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.archiveApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("archiveApplication (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.archiveApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("updateApplication (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            application: {
                id: "id",
                name: "name",
                slug: "slug",
                description: "description",
                websiteUrl: "websiteUrl",
                mode: "hosted",
                status: "active",
                redirectUris: ["redirectUris"],
                defaultAiKind: "personal",
                defaultVisibility: "PUBLIC",
                oauth: {
                    clientId: "clientId",
                    authorizationUrl: "authorizationUrl",
                    tokenUrl: "tokenUrl",
                    requirePKCE: true,
                },
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .patch("/applications/applicationId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.applications.updateApplication({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateApplication (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.updateApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("updateApplication (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.updateApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("updateApplication (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.updateApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("updateApplication (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.updateApplication({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("getApplicationMonetization (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            monetization: {
                applicationId: "applicationId",
                mode: "NONE",
                currency: "currency",
                fixedAmountMinor: 1,
                percentageBps: 1,
                maximumFeeMinor: 1,
                payoutSchedule: "MANUAL",
                status: "ACTIVE",
                revision: 1,
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId/monetization")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.applications.getApplicationMonetization({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getApplicationMonetization (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/monetization")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplicationMonetization({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getApplicationMonetization (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/monetization")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplicationMonetization({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getApplicationMonetization (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/monetization")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplicationMonetization({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getApplicationMonetization (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/monetization")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplicationMonetization({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("updateApplicationMonetization (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { mode: "NONE" };
        const rawResponseBody = {
            monetization: {
                applicationId: "applicationId",
                mode: "NONE",
                currency: "currency",
                fixedAmountMinor: 1,
                percentageBps: 1,
                maximumFeeMinor: 1,
                payoutSchedule: "MANUAL",
                status: "ACTIVE",
                revision: 1,
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .patch("/applications/applicationId/monetization")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.applications.updateApplicationMonetization({
            applicationId: "applicationId",
            mode: "NONE",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateApplicationMonetization (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { mode: "NONE" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId/monetization")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.updateApplicationMonetization({
                applicationId: "applicationId",
                mode: "NONE",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("updateApplicationMonetization (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { mode: "NONE" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId/monetization")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.updateApplicationMonetization({
                applicationId: "applicationId",
                mode: "NONE",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("updateApplicationMonetization (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { mode: "NONE" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId/monetization")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.updateApplicationMonetization({
                applicationId: "applicationId",
                mode: "NONE",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("updateApplicationMonetization (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { mode: "NONE" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/applications/applicationId/monetization")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.updateApplicationMonetization({
                applicationId: "applicationId",
                mode: "NONE",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("getApplicationWallet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            wallet: {
                applicationId: "applicationId",
                currency: "currency",
                availableAmountMinor: 1,
                reservedAmountMinor: 1,
                operationalAvailableAmountMinor: 1,
                operationalReservedAmountMinor: 1,
                pendingFeeEarningsMinor: 1,
                availableFeeEarningsMinor: 1,
            },
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId/wallet")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.applications.getApplicationWallet({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getApplicationWallet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/wallet")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplicationWallet({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getApplicationWallet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/wallet")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplicationWallet({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getApplicationWallet (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/wallet")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplicationWallet({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getApplicationWallet (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/wallet")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.getApplicationWallet({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("fundApplicationWallet (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId", amountMinor: 1, currency: "currency" };
        const rawResponseBody = {
            wallet: {
                applicationId: "applicationId",
                currency: "currency",
                availableAmountMinor: 1,
                reservedAmountMinor: 1,
                operationalAvailableAmountMinor: 1,
                operationalReservedAmountMinor: 1,
                pendingFeeEarningsMinor: 1,
                availableFeeEarningsMinor: 1,
            },
        };

        server
            .mockEndpoint()
            .post("/applications/applicationId/wallet/transfers")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.applications.fundApplicationWallet({
            "Idempotency-Key": "Idempotency-Key",
            applicationId: "applicationId",
            aiId: "aiId",
            amountMinor: 1,
            currency: "currency",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("fundApplicationWallet (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId", amountMinor: 1, currency: "foo" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/wallet/transfers")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.fundApplicationWallet({
                "Idempotency-Key": "idempotencyKey",
                applicationId: "applicationId",
                aiId: "aiId",
                amountMinor: 1,
                currency: "foo",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("fundApplicationWallet (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId", amountMinor: 1, currency: "foo" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/wallet/transfers")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.fundApplicationWallet({
                "Idempotency-Key": "idempotencyKey",
                applicationId: "applicationId",
                aiId: "aiId",
                amountMinor: 1,
                currency: "foo",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("fundApplicationWallet (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId", amountMinor: 1, currency: "foo" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/wallet/transfers")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.fundApplicationWallet({
                "Idempotency-Key": "idempotencyKey",
                applicationId: "applicationId",
                aiId: "aiId",
                amountMinor: 1,
                currency: "foo",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("fundApplicationWallet (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId", amountMinor: 1, currency: "foo" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/wallet/transfers")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.fundApplicationWallet({
                "Idempotency-Key": "idempotencyKey",
                applicationId: "applicationId",
                aiId: "aiId",
                amountMinor: 1,
                currency: "foo",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("listServiceAccounts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            serviceAccounts: [
                {
                    id: "id",
                    applicationId: "applicationId",
                    name: "name",
                    keyPrefix: "keyPrefix",
                    prefix: "prefix",
                    scopes: ["ais:read"],
                    status: "ACTIVE",
                    requestCount: 1,
                    lastUsedAt: "2024-01-15T09:30:00Z",
                    expiresAt: "2024-01-15T09:30:00Z",
                    revokedAt: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId/service-accounts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.applications.listServiceAccounts({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listServiceAccounts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/service-accounts")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.listServiceAccounts({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listServiceAccounts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/service-accounts")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.listServiceAccounts({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listServiceAccounts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/service-accounts")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.listServiceAccounts({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listServiceAccounts (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/service-accounts")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.listServiceAccounts({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createServiceAccount (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            serviceAccount: {
                id: "id",
                applicationId: "applicationId",
                name: "name",
                keyPrefix: "keyPrefix",
                prefix: "prefix",
                scopes: ["ais:read"],
                status: "ACTIVE",
                requestCount: 1,
                lastUsedAt: "2024-01-15T09:30:00Z",
                expiresAt: "2024-01-15T09:30:00Z",
                revokedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                apiKey: "apiKey",
            },
        };

        server
            .mockEndpoint()
            .post("/applications/applicationId/service-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.applications.createServiceAccount({
            applicationId: "applicationId",
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createServiceAccount (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/service-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.createServiceAccount({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createServiceAccount (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/service-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.createServiceAccount({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createServiceAccount (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/service-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.createServiceAccount({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createServiceAccount (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/service-accounts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.createServiceAccount({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("revokeServiceAccount (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            serviceAccount: {
                id: "id",
                applicationId: "applicationId",
                name: "name",
                keyPrefix: "keyPrefix",
                prefix: "prefix",
                scopes: ["ais:read"],
                status: "ACTIVE",
                requestCount: 1,
                lastUsedAt: "2024-01-15T09:30:00Z",
                expiresAt: "2024-01-15T09:30:00Z",
                revokedAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .delete("/applications/applicationId/service-accounts/serviceAccountId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.applications.revokeServiceAccount({
            applicationId: "applicationId",
            serviceAccountId: "serviceAccountId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("revokeServiceAccount (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/service-accounts/serviceAccountId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.revokeServiceAccount({
                applicationId: "applicationId",
                serviceAccountId: "serviceAccountId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("revokeServiceAccount (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/service-accounts/serviceAccountId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.revokeServiceAccount({
                applicationId: "applicationId",
                serviceAccountId: "serviceAccountId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("revokeServiceAccount (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/service-accounts/serviceAccountId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.revokeServiceAccount({
                applicationId: "applicationId",
                serviceAccountId: "serviceAccountId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("revokeServiceAccount (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/service-accounts/serviceAccountId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.applications.revokeServiceAccount({
                applicationId: "applicationId",
                serviceAccountId: "serviceAccountId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });
});
