// This file was auto-generated by Fern from our API Definition.

import * as Darwin from "../../../src/api/index";
import { DarwinClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("EnrollmentClient", () => {
    test("listEnrollmentLinks (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            enrollmentLinks: [
                {
                    id: "id",
                    applicationId: "applicationId",
                    name: "name",
                    codePrefix: "codePrefix",
                    mode: "HOSTED",
                    defaultAiKind: "PERSONAL",
                    defaultVisibility: "PUBLIC",
                    maxUses: 1,
                    useCount: 1,
                    expiresAt: "2024-01-15T09:30:00Z",
                    revokedAt: "2024-01-15T09:30:00Z",
                    settings: { key: "value" },
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-links")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.enrollment.listEnrollmentLinks({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listEnrollmentLinks (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-links")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.listEnrollmentLinks({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listEnrollmentLinks (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-links")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.listEnrollmentLinks({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listEnrollmentLinks (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-links")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.listEnrollmentLinks({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listEnrollmentLinks (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-links")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.listEnrollmentLinks({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createEnrollmentLink (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            enrollmentLink: {
                id: "id",
                applicationId: "applicationId",
                name: "name",
                codePrefix: "codePrefix",
                mode: "HOSTED",
                defaultAiKind: "PERSONAL",
                defaultVisibility: "PUBLIC",
                maxUses: 1,
                useCount: 1,
                expiresAt: "2024-01-15T09:30:00Z",
                revokedAt: "2024-01-15T09:30:00Z",
                settings: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                token: "token",
                url: "url",
            },
        };

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.enrollment.createEnrollmentLink({
            applicationId: "applicationId",
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createEnrollmentLink (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.createEnrollmentLink({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createEnrollmentLink (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.createEnrollmentLink({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createEnrollmentLink (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.createEnrollmentLink({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createEnrollmentLink (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-links")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.createEnrollmentLink({
                applicationId: "applicationId",
                name: "name",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("revokeEnrollmentLink (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            enrollmentLink: {
                id: "id",
                applicationId: "applicationId",
                name: "name",
                codePrefix: "codePrefix",
                mode: "HOSTED",
                defaultAiKind: "PERSONAL",
                defaultVisibility: "PUBLIC",
                maxUses: 1,
                useCount: 1,
                expiresAt: "2024-01-15T09:30:00Z",
                revokedAt: "2024-01-15T09:30:00Z",
                settings: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .delete("/applications/applicationId/enrollment-links/enrollmentLinkId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.enrollment.revokeEnrollmentLink({
            applicationId: "applicationId",
            enrollmentLinkId: "enrollmentLinkId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("revokeEnrollmentLink (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/enrollment-links/enrollmentLinkId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.revokeEnrollmentLink({
                applicationId: "applicationId",
                enrollmentLinkId: "enrollmentLinkId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("revokeEnrollmentLink (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/enrollment-links/enrollmentLinkId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.revokeEnrollmentLink({
                applicationId: "applicationId",
                enrollmentLinkId: "enrollmentLinkId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("revokeEnrollmentLink (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/enrollment-links/enrollmentLinkId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.revokeEnrollmentLink({
                applicationId: "applicationId",
                enrollmentLinkId: "enrollmentLinkId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("revokeEnrollmentLink (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/enrollment-links/enrollmentLinkId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.revokeEnrollmentLink({
                applicationId: "applicationId",
                enrollmentLinkId: "enrollmentLinkId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("createEnrollmentBatch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { externalReferences: ["externalReferences"] };
        const rawResponseBody = {
            batch: {
                id: "id",
                applicationId: "applicationId",
                status: "processing",
                totalCount: 1,
                readyCount: 1,
                failedCount: 1,
                expiresAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
            items: [
                {
                    id: "id",
                    externalReference: "externalReference",
                    status: "ready",
                    enrollmentUrl: "enrollmentUrl",
                    errorCode: "errorCode",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            page: { nextCursor: "nextCursor" },
        };

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-batches")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.enrollment.createEnrollmentBatch({
            applicationId: "applicationId",
            externalReferences: ["externalReferences"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createEnrollmentBatch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { externalReferences: ["externalReferences", "externalReferences"] };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-batches")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.createEnrollmentBatch({
                applicationId: "applicationId",
                externalReferences: ["externalReferences", "externalReferences"],
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createEnrollmentBatch (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { externalReferences: ["externalReferences", "externalReferences"] };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-batches")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.createEnrollmentBatch({
                applicationId: "applicationId",
                externalReferences: ["externalReferences", "externalReferences"],
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createEnrollmentBatch (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { externalReferences: ["externalReferences", "externalReferences"] };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-batches")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.createEnrollmentBatch({
                applicationId: "applicationId",
                externalReferences: ["externalReferences", "externalReferences"],
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createEnrollmentBatch (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { externalReferences: ["externalReferences", "externalReferences"] };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/enrollment-batches")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.createEnrollmentBatch({
                applicationId: "applicationId",
                externalReferences: ["externalReferences", "externalReferences"],
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("getEnrollmentBatch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            batch: {
                id: "id",
                applicationId: "applicationId",
                status: "processing",
                totalCount: 1,
                readyCount: 1,
                failedCount: 1,
                expiresAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
            items: [
                {
                    id: "id",
                    externalReference: "externalReference",
                    status: "ready",
                    enrollmentUrl: "enrollmentUrl",
                    errorCode: "errorCode",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            page: { nextCursor: "nextCursor" },
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-batches/batchId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.enrollment.getEnrollmentBatch({
            applicationId: "applicationId",
            batchId: "batchId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getEnrollmentBatch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-batches/batchId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.getEnrollmentBatch({
                applicationId: "applicationId",
                batchId: "batchId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getEnrollmentBatch (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-batches/batchId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.getEnrollmentBatch({
                applicationId: "applicationId",
                batchId: "batchId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getEnrollmentBatch (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-batches/batchId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.getEnrollmentBatch({
                applicationId: "applicationId",
                batchId: "batchId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getEnrollmentBatch (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/enrollment-batches/batchId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.enrollment.getEnrollmentBatch({
                applicationId: "applicationId",
                batchId: "batchId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });
});
