// This file was auto-generated by Fern from our API Definition.

import * as Darwin from "../../../src/api/index";
import { DarwinClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("UsersClient", () => {
    test("resolveApplicationUser (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { externalUserReference: "externalUserReference" };
        const rawResponseBody = {
            status: "READY",
            darwinUserRef: "darwinUserRef",
            darwinAiRef: "darwinAiRef",
            verificationMethod: "verificationMethod",
            consentScopes: ["consentScopes"],
        };

        server
            .mockEndpoint()
            .post("/applications/applicationId/users/resolve")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.users.resolveApplicationUser({
            applicationId: "applicationId",
            externalUserReference: "externalUserReference",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("resolveApplicationUser (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { externalUserReference: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/users/resolve")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.resolveApplicationUser({
                applicationId: "applicationId",
                externalUserReference: "x",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("resolveApplicationUser (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { externalUserReference: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/users/resolve")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.resolveApplicationUser({
                applicationId: "applicationId",
                externalUserReference: "x",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("resolveApplicationUser (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { externalUserReference: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/users/resolve")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.resolveApplicationUser({
                applicationId: "applicationId",
                externalUserReference: "x",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("resolveApplicationUser (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { externalUserReference: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/users/resolve")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.resolveApplicationUser({
                applicationId: "applicationId",
                externalUserReference: "x",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("listApplicationAIs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            ais: [
                {
                    id: "id",
                    applicationId: "applicationId",
                    aiId: "aiId",
                    externalReference: "externalReference",
                    status: "ACTIVE",
                    visibility: "PUBLIC",
                    permissions: ["permissions"],
                    metadata: { key: "value" },
                    linkedAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/applications/applicationId/ais")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.users.listApplicationAIs({
            applicationId: "applicationId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listApplicationAIs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/ais")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.listApplicationAIs({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listApplicationAIs (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/ais")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.listApplicationAIs({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listApplicationAIs (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/ais")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.listApplicationAIs({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listApplicationAIs (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/applications/applicationId/ais")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.listApplicationAIs({
                applicationId: "applicationId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("linkApplicationAI (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId" };
        const rawResponseBody = {
            aiLink: {
                id: "id",
                applicationId: "applicationId",
                aiId: "aiId",
                externalReference: "externalReference",
                status: "ACTIVE",
                visibility: "PUBLIC",
                permissions: ["permissions"],
                metadata: { key: "value" },
                linkedAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                aiIdentity: {
                    id: "id",
                    kind: "PERSONAL",
                    name: "name",
                    handle: "handle",
                    avatarUrl: "avatarUrl",
                    description: "description",
                    visibility: "PUBLIC",
                },
            },
        };

        server
            .mockEndpoint()
            .post("/applications/applicationId/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.users.linkApplicationAi({
            applicationId: "applicationId",
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("linkApplicationAI (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.linkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("linkApplicationAI (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.linkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("linkApplicationAI (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.linkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("linkApplicationAI (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { aiId: "aiId" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/applications/applicationId/ais")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.linkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("unlinkApplicationAI (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            aiLink: {
                id: "id",
                applicationId: "applicationId",
                aiId: "aiId",
                externalReference: "externalReference",
                status: "ACTIVE",
                visibility: "PUBLIC",
                permissions: ["permissions"],
                metadata: { key: "value" },
                linkedAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                aiIdentity: {
                    id: "id",
                    kind: "PERSONAL",
                    name: "name",
                    handle: "handle",
                    avatarUrl: "avatarUrl",
                    description: "description",
                    visibility: "PUBLIC",
                },
            },
        };

        server
            .mockEndpoint()
            .delete("/applications/applicationId/ais/aiId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.connect.users.unlinkApplicationAi({
            applicationId: "applicationId",
            aiId: "aiId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("unlinkApplicationAI (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/ais/aiId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.unlinkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("unlinkApplicationAI (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/ais/aiId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.unlinkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("unlinkApplicationAI (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/ais/aiId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.unlinkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("unlinkApplicationAI (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/applications/applicationId/ais/aiId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.connect.users.unlinkApplicationAi({
                applicationId: "applicationId",
                aiId: "aiId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });
});
