// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         applicationId: "applicationId",
 *         serviceAccountId: "serviceAccountId"
 *     }
 */
export interface RevokeServiceAccountApplicationsRequest {
    applicationId: string;
    serviceAccountId: string;
}
