// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         applicationId: "applicationId",
 *         mode: "NONE"
 *     }
 */
export interface UpdateApplicationMonetizationRequest {
    applicationId: string;
    mode: UpdateApplicationMonetizationRequest.Mode;
    currency?: string;
    fixedAmountMinor?: number;
    percentageBps?: number;
    /** Required for percentage fees. */
    maximumFeeMinor?: number;
    /** Stores the desired payout cadence. Automatic and manual fee-earnings payout operations remain preview until their public endpoints ship. */
    payoutSchedule?: UpdateApplicationMonetizationRequest.PayoutSchedule;
}

export namespace UpdateApplicationMonetizationRequest {
    export const Mode = {
        None: "NONE",
        Fixed: "FIXED",
        Percentage: "PERCENTAGE",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    /** Stores the desired payout cadence. Automatic and manual fee-earnings payout operations remain preview until their public endpoints ship. */
    export const PayoutSchedule = {
        Manual: "MANUAL",
        Weekly: "WEEKLY",
        Monthly: "MONTHLY",
    } as const;
    export type PayoutSchedule = (typeof PayoutSchedule)[keyof typeof PayoutSchedule];
}
