// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../../../../../../index.js";

/**
 * @example
 *     {
 *         applicationId: "applicationId"
 *     }
 */
export interface UpdateApplicationRequest {
    applicationId: string;
    name?: string;
    description?: string | null;
    websiteUrl?: string | null;
    mode?: UpdateApplicationRequest.Mode;
    redirectUris?: string[];
    defaultAiKind?: UpdateApplicationRequest.DefaultAiKind;
    defaultVisibility?: Darwin.Visibility;
    metadata?: Record<string, unknown>;
}

export namespace UpdateApplicationRequest {
    export const Mode = {
        Hosted: "HOSTED",
        Embedded: "EMBEDDED",
        Hybrid: "HYBRID",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
    export const DefaultAiKind = {
        Personal: "PERSONAL",
        Business: "BUSINESS",
    } as const;
    export type DefaultAiKind = (typeof DefaultAiKind)[keyof typeof DefaultAiKind];
}
