// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         applicationId: "applicationId",
 *         batchId: "batchId"
 *     }
 */
export interface GetEnrollmentBatchEnrollmentRequest {
    applicationId: string;
    batchId: string;
    limit?: number;
    cursor?: string;
}
