// This file was auto-generated by Fern from our API Definition.

import * as Darwin from "../../src/api/index";
import { DarwinClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TransactionsClient", () => {
    test("createDealTransaction (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            state: "ready",
            transaction: {
                id: "id",
                transactionId: "transactionId",
                goalId: "goalId",
                dealId: "dealId",
                mode: "BUY",
                reservedCapMinor: 1,
                subtotalMinor: 1,
                darwinFeeMinor: 1,
                feeBps: 1,
                feeAttributionReason: "feeAttributionReason",
                feePolicyVersion: 1,
                taxAmountMinor: 1,
                settledAmountMinor: 1,
                releasedAmountMinor: 1,
                refundedAmountMinor: 1,
                currency: "currency",
                status: "status",
                settlementMode: "fixed",
                sellerAcceptanceStatus: "sellerAcceptanceStatus",
                customerAccountStatus: "customerAccountStatus",
                fulfillmentStatus: "fulfillmentStatus",
                fundedAt: "2024-01-15T09:30:00Z",
                transferredAt: "2024-01-15T09:30:00Z",
                refundedAt: "2024-01-15T09:30:00Z",
                disputedAt: "2024-01-15T09:30:00Z",
                canceledAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
            fundingAmountMinor: 1,
            fundingRail: "fundingRail",
            clientSecret: "clientSecret",
        };

        server
            .mockEndpoint()
            .post("/deals/dealId/transactions")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.createDealTransaction({
            "Idempotency-Key": "Idempotency-Key",
            dealId: "dealId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createDealTransaction (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/deals/dealId/transactions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createDealTransaction({
                "Idempotency-Key": "idempotencyKey",
                dealId: "dealId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("createDealTransaction (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/deals/dealId/transactions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createDealTransaction({
                "Idempotency-Key": "idempotencyKey",
                dealId: "dealId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("createDealTransaction (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/deals/dealId/transactions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createDealTransaction({
                "Idempotency-Key": "idempotencyKey",
                dealId: "dealId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("createDealTransaction (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/deals/dealId/transactions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.createDealTransaction({
                "Idempotency-Key": "idempotencyKey",
                dealId: "dealId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("listTransactions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            transactions: [
                {
                    id: "id",
                    transactionId: "transactionId",
                    goalId: "goalId",
                    dealId: "dealId",
                    mode: "BUY",
                    reservedCapMinor: 1,
                    subtotalMinor: 1,
                    darwinFeeMinor: 1,
                    feeBps: 1,
                    feeAttributionReason: "feeAttributionReason",
                    feePolicyVersion: 1,
                    taxAmountMinor: 1,
                    settledAmountMinor: 1,
                    releasedAmountMinor: 1,
                    refundedAmountMinor: 1,
                    currency: "currency",
                    status: "status",
                    settlementMode: "fixed",
                    sellerAcceptanceStatus: "sellerAcceptanceStatus",
                    customerAccountStatus: "customerAccountStatus",
                    fulfillmentStatus: "fulfillmentStatus",
                    fundedAt: "2024-01-15T09:30:00Z",
                    transferredAt: "2024-01-15T09:30:00Z",
                    refundedAt: "2024-01-15T09:30:00Z",
                    disputedAt: "2024-01-15T09:30:00Z",
                    canceledAt: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
        };

        server.mockEndpoint().get("/transactions").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.transactions.listTransactions();
        expect(response).toEqual(rawResponseBody);
    });

    test("listTransactions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/transactions").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transactions.listTransactions();
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("listTransactions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/transactions").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transactions.listTransactions();
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("listTransactions (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/transactions").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transactions.listTransactions();
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("listTransactions (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/transactions").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.transactions.listTransactions();
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("getTransaction (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            transaction: {
                id: "id",
                transactionId: "transactionId",
                goalId: "goalId",
                dealId: "dealId",
                mode: "BUY",
                reservedCapMinor: 1,
                subtotalMinor: 1,
                darwinFeeMinor: 1,
                feeBps: 1,
                feeAttributionReason: "feeAttributionReason",
                feePolicyVersion: 1,
                taxAmountMinor: 1,
                settledAmountMinor: 1,
                releasedAmountMinor: 1,
                refundedAmountMinor: 1,
                currency: "currency",
                status: "status",
                settlementMode: "fixed",
                sellerAcceptanceStatus: "sellerAcceptanceStatus",
                customerAccountStatus: "customerAccountStatus",
                fulfillmentStatus: "fulfillmentStatus",
                fundedAt: "2024-01-15T09:30:00Z",
                transferredAt: "2024-01-15T09:30:00Z",
                refundedAt: "2024-01-15T09:30:00Z",
                disputedAt: "2024-01-15T09:30:00Z",
                canceledAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/transactions/transactionId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.getTransaction({
            transactionId: "transactionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getTransaction (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/transactions/transactionId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getTransaction({
                transactionId: "transactionId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getTransaction (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/transactions/transactionId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getTransaction({
                transactionId: "transactionId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getTransaction (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/transactions/transactionId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getTransaction({
                transactionId: "transactionId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getTransaction (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/transactions/transactionId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getTransaction({
                transactionId: "transactionId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("getTransactionAccountRequirement (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            accountRequirement: {
                transactionId: "transactionId",
                transactionStatus: "transactionStatus",
                requirement: "NONE",
                providerKey: "providerKey",
                requiredScopes: ["requiredScopes"],
                allowedRetention: ["REQUEST_ONLY"],
                status: "NOT_REQUIRED",
                missingScopes: ["missingScopes"],
            },
        };

        server
            .mockEndpoint()
            .get("/transactions/transactionId/account-requirement")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.getTransactionAccountRequirement({
            transactionId: "transactionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getTransactionAccountRequirement (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/transactions/transactionId/account-requirement")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getTransactionAccountRequirement({
                transactionId: "transactionId",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("getTransactionAccountRequirement (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/transactions/transactionId/account-requirement")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getTransactionAccountRequirement({
                transactionId: "transactionId",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("getTransactionAccountRequirement (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/transactions/transactionId/account-requirement")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getTransactionAccountRequirement({
                transactionId: "transactionId",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("getTransactionAccountRequirement (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/transactions/transactionId/account-requirement")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.getTransactionAccountRequirement({
                transactionId: "transactionId",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("actOnTransaction (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { action: "CANCEL" };
        const rawResponseBody = {
            transaction: {
                id: "id",
                transactionId: "transactionId",
                goalId: "goalId",
                dealId: "dealId",
                mode: "BUY",
                reservedCapMinor: 1,
                subtotalMinor: 1,
                darwinFeeMinor: 1,
                feeBps: 1,
                feeAttributionReason: "feeAttributionReason",
                feePolicyVersion: 1,
                taxAmountMinor: 1,
                settledAmountMinor: 1,
                releasedAmountMinor: 1,
                refundedAmountMinor: 1,
                currency: "currency",
                status: "status",
                settlementMode: "fixed",
                sellerAcceptanceStatus: "sellerAcceptanceStatus",
                customerAccountStatus: "customerAccountStatus",
                fulfillmentStatus: "fulfillmentStatus",
                fundedAt: "2024-01-15T09:30:00Z",
                transferredAt: "2024-01-15T09:30:00Z",
                refundedAt: "2024-01-15T09:30:00Z",
                disputedAt: "2024-01-15T09:30:00Z",
                canceledAt: "2024-01-15T09:30:00Z",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/transactions/transactionId/actions")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.actOnTransaction({
            "Idempotency-Key": "Idempotency-Key",
            transactionId: "transactionId",
            action: "CANCEL",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("actOnTransaction (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { action: "CANCEL" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/transactions/transactionId/actions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.actOnTransaction({
                "Idempotency-Key": "idempotencyKey",
                transactionId: "transactionId",
                action: "CANCEL",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("actOnTransaction (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { action: "CANCEL" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/transactions/transactionId/actions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.actOnTransaction({
                "Idempotency-Key": "idempotencyKey",
                transactionId: "transactionId",
                action: "CANCEL",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("actOnTransaction (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { action: "CANCEL" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/transactions/transactionId/actions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.actOnTransaction({
                "Idempotency-Key": "idempotencyKey",
                transactionId: "transactionId",
                action: "CANCEL",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("actOnTransaction (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { action: "CANCEL" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/transactions/transactionId/actions")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.actOnTransaction({
                "Idempotency-Key": "idempotencyKey",
                transactionId: "transactionId",
                action: "CANCEL",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });

    test("authorizeTransactionPayment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            type: "STRIPE_SHARED_PAYMENT_TOKEN",
            networkProfileId: "networkProfileId",
            grantedToken: "grantedToken",
        };
        const rawResponseBody = {
            paymentAuthorization: {
                authorizationId: "authorizationId",
                transactionId: "transactionId",
                status: "status",
                providerPaymentIntentId: "providerPaymentIntentId",
                nextActionRequired: true,
                clientSecret: "clientSecret",
            },
        };

        server
            .mockEndpoint()
            .post("/transactions/transactionId/payment-authorizations")
            .header("Idempotency-Key", "Idempotency-Key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.transactions.authorizeTransactionPayment({
            "Idempotency-Key": "Idempotency-Key",
            transactionId: "transactionId",
            type: "STRIPE_SHARED_PAYMENT_TOKEN",
            networkProfileId: "networkProfileId",
            grantedToken: "grantedToken",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("authorizeTransactionPayment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            type: "STRIPE_SHARED_PAYMENT_TOKEN",
            networkProfileId: "networkProfileId",
            grantedToken: "grantedToken",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/transactions/transactionId/payment-authorizations")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.authorizeTransactionPayment({
                "Idempotency-Key": "idempotencyKey",
                transactionId: "transactionId",
                type: "STRIPE_SHARED_PAYMENT_TOKEN",
                networkProfileId: "networkProfileId",
                grantedToken: "grantedToken",
            });
        }).rejects.toThrow(Darwin.BadRequestError);
    });

    test("authorizeTransactionPayment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            type: "STRIPE_SHARED_PAYMENT_TOKEN",
            networkProfileId: "networkProfileId",
            grantedToken: "grantedToken",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/transactions/transactionId/payment-authorizations")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.authorizeTransactionPayment({
                "Idempotency-Key": "idempotencyKey",
                transactionId: "transactionId",
                type: "STRIPE_SHARED_PAYMENT_TOKEN",
                networkProfileId: "networkProfileId",
                grantedToken: "grantedToken",
            });
        }).rejects.toThrow(Darwin.UnauthorizedError);
    });

    test("authorizeTransactionPayment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            type: "STRIPE_SHARED_PAYMENT_TOKEN",
            networkProfileId: "networkProfileId",
            grantedToken: "grantedToken",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/transactions/transactionId/payment-authorizations")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.authorizeTransactionPayment({
                "Idempotency-Key": "idempotencyKey",
                transactionId: "transactionId",
                type: "STRIPE_SHARED_PAYMENT_TOKEN",
                networkProfileId: "networkProfileId",
                grantedToken: "grantedToken",
            });
        }).rejects.toThrow(Darwin.ForbiddenError);
    });

    test("authorizeTransactionPayment (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DarwinClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            type: "STRIPE_SHARED_PAYMENT_TOKEN",
            networkProfileId: "networkProfileId",
            grantedToken: "grantedToken",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/transactions/transactionId/payment-authorizations")
            .header("Idempotency-Key", "idempotencyKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.transactions.authorizeTransactionPayment({
                "Idempotency-Key": "idempotencyKey",
                transactionId: "transactionId",
                type: "STRIPE_SHARED_PAYMENT_TOKEN",
                networkProfileId: "networkProfileId",
                grantedToken: "grantedToken",
            });
        }).rejects.toThrow(Darwin.NotFoundError);
    });
});
