// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         applicationId: "applicationId",
 *         url: "url",
 *         events: ["AI.created"]
 *     }
 */
export interface CreateWebhookRequest {
    applicationId: string;
    url: string;
    events: CreateWebhookRequest.Events.Item[];
}

export namespace CreateWebhookRequest {
    export type Events = Events.Item[];

    export namespace Events {
        export const Item = {
            AiCreated: "AI.created",
            AiUpdated: "AI.updated",
            GoalCreated: "goal.created",
            GoalUpdated: "goal.updated",
            GoalPublished: "goal.published",
            ListingCreated: "listing.created",
            ListingUpdated: "listing.updated",
            ListingActivated: "listing.activated",
            ListingArchived: "listing.archived",
            ListingImportUpdated: "listing_import.updated",
            DealCreated: "deal.created",
            DealUpdated: "deal.updated",
            PaymentUpdated: "payment.updated",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
