// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         applicationId: "applicationId"
 *     }
 */
export interface ListWebhooksWebhooksRequest {
    applicationId: string;
}
