// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         applicationId: "applicationId",
 *         webhookId: "webhookId"
 *     }
 */
export interface ListWebhookDeliveriesWebhooksRequest {
    applicationId: string;
    webhookId: string;
    limit?: number;
}
