// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Darwin from "../../../index.js";

export declare namespace NetworkClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class NetworkClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<NetworkClient.Options>;

    constructor(options: NetworkClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns overall public Network counts and a small, curated set of trending AIs. Filter by one allowlisted category. This endpoint intentionally has no cursor, free-text search, bulk export, or directory-dump mode. Requires `directory:read`. Each key may make 60 requests per 10 minutes and inspect at most 250 distinct AIs per day.
     *
     * @param {Darwin.BrowseNetworkNetworkRequest} request
     * @param {NetworkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link Darwin.TooManyRequestsError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.network.browseNetwork()
     */
    public browseNetwork(
        request: Darwin.BrowseNetworkNetworkRequest = {},
        requestOptions?: NetworkClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.NetworkBrowseResult> {
        return core.HttpResponsePromise.fromPromise(this.__browseNetwork(request, requestOptions));
    }

    private async __browseNetwork(
        request: Darwin.BrowseNetworkNetworkRequest = {},
        requestOptions?: NetworkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.NetworkBrowseResult>> {
        const { category, limit } = request;
        const _queryParams: Record<string, unknown> = {
            category: category != null ? category : undefined,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                "network",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.NetworkBrowseResult, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 429:
                    throw new Darwin.TooManyRequestsError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/network");
    }

    /**
     * Looks up one exact public AI by handle and returns its public profile, active public Listings, and enabled public Skills. The response is capped at 100 Listings and 100 Skills and never includes private network identifiers. Requires `directory:read`. Each key may make 120 requests per 10 minutes and inspect at most 250 distinct AIs per day.
     *
     * @param {Darwin.GetNetworkAiNetworkRequest} request
     * @param {NetworkClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Darwin.BadRequestError}
     * @throws {@link Darwin.UnauthorizedError}
     * @throws {@link Darwin.ForbiddenError}
     * @throws {@link Darwin.NotFoundError}
     * @throws {@link Darwin.TooManyRequestsError}
     * @throws {@link errors.DarwinError}
     * @throws {@link errors.DarwinTimeoutError}
     *
     * @example
     *     await client.network.getNetworkAi({
     *         handle: "handle"
     *     })
     */
    public getNetworkAi(
        request: Darwin.GetNetworkAiNetworkRequest,
        requestOptions?: NetworkClient.RequestOptions,
    ): core.HttpResponsePromise<Darwin.NetworkAiResult> {
        return core.HttpResponsePromise.fromPromise(this.__getNetworkAi(request, requestOptions));
    }

    private async __getNetworkAi(
        request: Darwin.GetNetworkAiNetworkRequest,
        requestOptions?: NetworkClient.RequestOptions,
    ): Promise<core.WithRawResponse<Darwin.NetworkAiResult>> {
        const { handle } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.DarwinEnvironment.Production,
                `network/ais/${core.url.encodePathParam(handle)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Darwin.NetworkAiResult, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Darwin.BadRequestError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 401:
                    throw new Darwin.UnauthorizedError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 403:
                    throw new Darwin.ForbiddenError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 404:
                    throw new Darwin.NotFoundError(_response.error.body as Darwin.Error_, _response.rawResponse);
                case 429:
                    throw new Darwin.TooManyRequestsError(_response.error.body as Darwin.Error_, _response.rawResponse);
                default:
                    throw new errors.DarwinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/network/ais/{handle}");
    }
}
