// This file was auto-generated by Fern from our API Definition.

import { AccountClient } from "./api/resources/account/client/Client.js";
import { AisClient } from "./api/resources/ais/client/Client.js";
import { ConnectClient } from "./api/resources/connect/client/Client.js";
import { ConnectionsClient } from "./api/resources/connections/client/Client.js";
import { ConversationsClient } from "./api/resources/conversations/client/Client.js";
import { DealsClient } from "./api/resources/deals/client/Client.js";
import { DeploymentClient } from "./api/resources/deployment/client/Client.js";
import { GoalsClient } from "./api/resources/goals/client/Client.js";
import { IntegrationsClient } from "./api/resources/integrations/client/Client.js";
import { ListingsClient } from "./api/resources/listings/client/Client.js";
import { NetworkClient } from "./api/resources/network/client/Client.js";
import { NotificationsClient } from "./api/resources/notifications/client/Client.js";
import { OutcomesClient } from "./api/resources/outcomes/client/Client.js";
import { PermissionsClient } from "./api/resources/permissions/client/Client.js";
import { ReputationClient } from "./api/resources/reputation/client/Client.js";
import { RequestsClient } from "./api/resources/requests/client/Client.js";
import { SearchClient } from "./api/resources/search/client/Client.js";
import { SkillsClient } from "./api/resources/skills/client/Client.js";
import { SupplyClient } from "./api/resources/supply/client/Client.js";
import { TasksClient } from "./api/resources/tasks/client/Client.js";
import { ToolsClient } from "./api/resources/tools/client/Client.js";
import { TransactionsClient } from "./api/resources/transactions/client/Client.js";
import { UsageClient } from "./api/resources/usage/client/Client.js";
import { VerificationClient } from "./api/resources/verification/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace DarwinClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class DarwinClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DarwinClient.Options>;
    protected _account: AccountClient | undefined;
    protected _ais: AisClient | undefined;
    protected _listings: ListingsClient | undefined;
    protected _reputation: ReputationClient | undefined;
    protected _permissions: PermissionsClient | undefined;
    protected _notifications: NotificationsClient | undefined;
    protected _usage: UsageClient | undefined;
    protected _verification: VerificationClient | undefined;
    protected _deployment: DeploymentClient | undefined;
    protected _integrations: IntegrationsClient | undefined;
    protected _connections: ConnectionsClient | undefined;
    protected _skills: SkillsClient | undefined;
    protected _conversations: ConversationsClient | undefined;
    protected _requests: RequestsClient | undefined;
    protected _tools: ToolsClient | undefined;
    protected _tasks: TasksClient | undefined;
    protected _goals: GoalsClient | undefined;
    protected _network: NetworkClient | undefined;
    protected _search: SearchClient | undefined;
    protected _deals: DealsClient | undefined;
    protected _transactions: TransactionsClient | undefined;
    protected _outcomes: OutcomesClient | undefined;
    protected _connect: ConnectClient | undefined;
    protected _supply: SupplyClient | undefined;

    constructor(options: DarwinClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get account(): AccountClient {
        return (this._account ??= new AccountClient(this._options));
    }

    public get ais(): AisClient {
        return (this._ais ??= new AisClient(this._options));
    }

    public get listings(): ListingsClient {
        return (this._listings ??= new ListingsClient(this._options));
    }

    public get reputation(): ReputationClient {
        return (this._reputation ??= new ReputationClient(this._options));
    }

    public get permissions(): PermissionsClient {
        return (this._permissions ??= new PermissionsClient(this._options));
    }

    public get notifications(): NotificationsClient {
        return (this._notifications ??= new NotificationsClient(this._options));
    }

    public get usage(): UsageClient {
        return (this._usage ??= new UsageClient(this._options));
    }

    public get verification(): VerificationClient {
        return (this._verification ??= new VerificationClient(this._options));
    }

    public get deployment(): DeploymentClient {
        return (this._deployment ??= new DeploymentClient(this._options));
    }

    public get integrations(): IntegrationsClient {
        return (this._integrations ??= new IntegrationsClient(this._options));
    }

    public get connections(): ConnectionsClient {
        return (this._connections ??= new ConnectionsClient(this._options));
    }

    public get skills(): SkillsClient {
        return (this._skills ??= new SkillsClient(this._options));
    }

    public get conversations(): ConversationsClient {
        return (this._conversations ??= new ConversationsClient(this._options));
    }

    public get requests(): RequestsClient {
        return (this._requests ??= new RequestsClient(this._options));
    }

    public get tools(): ToolsClient {
        return (this._tools ??= new ToolsClient(this._options));
    }

    public get tasks(): TasksClient {
        return (this._tasks ??= new TasksClient(this._options));
    }

    public get goals(): GoalsClient {
        return (this._goals ??= new GoalsClient(this._options));
    }

    public get network(): NetworkClient {
        return (this._network ??= new NetworkClient(this._options));
    }

    public get search(): SearchClient {
        return (this._search ??= new SearchClient(this._options));
    }

    public get deals(): DealsClient {
        return (this._deals ??= new DealsClient(this._options));
    }

    public get transactions(): TransactionsClient {
        return (this._transactions ??= new TransactionsClient(this._options));
    }

    public get outcomes(): OutcomesClient {
        return (this._outcomes ??= new OutcomesClient(this._options));
    }

    public get connect(): ConnectClient {
        return (this._connect ??= new ConnectClient(this._options));
    }

    public get supply(): SupplyClient {
        return (this._supply ??= new SupplyClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
