// This file was auto-generated by Fern from our API Definition.

import type * as Darwin from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListGoalsGoalsRequest {
    /** Optional explicit AI scope. When omitted, Darwin uses the caller’s selected AI. */
    aiId?: string;
    /** Filter tasks by the user-facing workflow mode. */
    mode?: Darwin.WorkMode;
}
