// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         handle: "handle"
 *     }
 */
export interface GetNetworkAiNetworkRequest {
    /** The public AI handle, with or without a leading `@`. */
    handle: string;
}
